package model;
// Generated 6 janv. 2016 11:04:49 by Hibernate Tools 4.3.1.Final

/**
 * HistoriqueTaux generated by hbm2java
 */
public class HistoriqueTaux implements java.io.Serializable {

	private HistoriqueTauxId id;
	private Pret pret;
	private Long taux;

	public HistoriqueTaux() {
	}

	public HistoriqueTaux(HistoriqueTauxId id, Pret pret) {
		this.id = id;
		this.pret = pret;
	}

	public HistoriqueTaux(HistoriqueTauxId id, Pret pret, Long taux) {
		this.id = id;
		this.pret = pret;
		this.taux = taux;
	}

	public HistoriqueTauxId getId() {
		return this.id;
	}

	public void setId(HistoriqueTauxId id) {
		this.id = id;
	}

	public Pret getPret() {
		return this.pret;
	}

	public void setPret(Pret pret) {
		this.pret = pret;
	}

	public Long getTaux() {
		return this.taux;
	}

	public void setTaux(Long taux) {
		this.taux = taux;
	}

}
