package model;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;

// default package
// Generated 6 janv. 2016 11:04:49 by Hibernate Tools 4.3.1.Final

/**
 * StatutPret generated by hbm2java
 */
public class StatutPret implements java.io.Serializable {

	private int id_statut_pret;
	private String intituleStatutPret;

	public StatutPret() {
	}

	public StatutPret(String intituleStatutPret) {
		this.intituleStatutPret = intituleStatutPret;
	}
	public StatutPret(int id_statut_pret, String intituleStatutPret) {
		this.id_statut_pret = id_statut_pret;
		this.intituleStatutPret = intituleStatutPret;
	}
	public int getid_statut_pret() {
		return this.id_statut_pret;
	}

	public void setid_statut_pret(int id_statut_pret) {
		this.id_statut_pret = id_statut_pret;
	}

	public String getString() {
		return this.intituleStatutPret;
	}

	public void setString(String intituleStatutPret) {
		this.intituleStatutPret = intituleStatutPret;
	}

	public String toString(){
		return Integer.toString(this.id_statut_pret)+" "+this.intituleStatutPret;
	}
	public static ArrayList<StatutPret> selectStatutPret(Connection conn){
		Statement statement = null;
		ResultSet resultat= null;
		ArrayList<StatutPret> statutPrets=new ArrayList<StatutPret>();
		try {
			statement = conn.createStatement();

	        /* Exécution d'une requète de lecture */
	        resultat = statement.executeQuery( "select * from statut_pret" );
	 
	        /* Récupération des données du résultat de la requète de lecture */
	        while ( resultat.next() ) {
	        	statutPrets.add(new StatutPret(Integer.parseInt(resultat.getString(1)),resultat.getString(2)));
		}
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
        
		return statutPrets;
	}
}
