package model;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;

// default package
// Generated 6 janv. 2016 11:04:49 by Hibernate Tools 4.3.1.Final

/**
 * TypePret generated by hbm2java
 */
public class TypePret implements java.io.Serializable {

	private int id_type_pret;
	private String intitule;

	public TypePret() {
	}

	public int getIdTypePret() {
		return this.id_type_pret;
	}

	public TypePret(int id_type_pret, String intitule) {
		this.id_type_pret = id_type_pret;
		this.intitule = intitule;
	}
	
	public void setIdTypePret(int id_type_pret) {
		this.id_type_pret = id_type_pret;
	}

	public String getIntitule() {
		return this.intitule;
	}

	public void setIntitule(String intitule) {
		this.intitule = intitule;
	}
	
	public String toString(){
		return Integer.toString(this.getIdTypePret())+" "+this.intitule;
	}
	
	public static ArrayList<TypePret> selectTypePret(Connection conn){
		Statement statement = null;
		ResultSet resultat= null;
		ArrayList<TypePret> typePrets=new ArrayList<TypePret>();
		try {
			statement = conn.createStatement();

	        /* Exécution d'une requète de lecture */
	        resultat = statement.executeQuery( "select * from type_pret" );
	 
	        /* Récupération des données du résultat de la requète de lecture */
	        while ( resultat.next() ) {
	        	typePrets.add(new TypePret(Integer.parseInt(resultat.getString(1)),resultat.getString(2)));
		}
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
        
		return typePrets;
	}

}
