package model;
// Generated 6 janv. 2016 11:04:49 by Hibernate Tools 4.3.1.Final

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;

/**
 * TypeUtilisateur generated by hbm2java
 */
public class TypeUtilisateur implements java.io.Serializable {

	private int idTypeUtilisateur;
	private String nom;
	
	public TypeUtilisateur() {
	}

	public TypeUtilisateur(int idTypeUtilisateur) {
		this.idTypeUtilisateur = idTypeUtilisateur;
	}

	public TypeUtilisateur(int idTypeUtilisateur, String nom) {
		this.idTypeUtilisateur = idTypeUtilisateur;
		this.nom = nom;
	}

	public int getIdTypeUtilisateur() {
		return this.idTypeUtilisateur;
	}

	public void setIdTypeUtilisateur(int idTypeUtilisateur) {
		this.idTypeUtilisateur = idTypeUtilisateur;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}
	

	public String toString(){
		return Integer.toString(this.idTypeUtilisateur)+" "+this.nom;
	}
	public static ArrayList<TypeUtilisateur> selectTypeUtilisateur(Connection conn){
		Statement statement = null;
		ResultSet resultat= null;
		ArrayList<TypeUtilisateur> typeUtilisateurs=new ArrayList<TypeUtilisateur>();
		try {
			statement = conn.createStatement();

	        /* Exécution d'une requète de lecture */
	        resultat = statement.executeQuery( "select * from type_utilisateur" );
	 
	        /* Récupération des données du résultat de la requète de lecture */
	        while ( resultat.next() ) {
	        	typeUtilisateurs.add(new TypeUtilisateur(Integer.parseInt(resultat.getString(1)),resultat.getString(2)));
		}
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
        
		return typeUtilisateurs;
	}


}
