package model;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;




/**
 * TypeClient generated by hbm2java
 */
public class TypeClient implements java.io.Serializable {

	private int idTypeClient;
	private String nom;

	
	public TypeClient() {
	}

	public TypeClient(int idTypeClient) {
		this.idTypeClient = idTypeClient;
	}

	public TypeClient(int idTypeClient, String nom) {
		this.idTypeClient = idTypeClient;
		this.nom = nom;
	}

	public int getIdTypeClient() {
		return this.idTypeClient;
	}

	public void setIdTypeClient(int idTypeClient) {
		this.idTypeClient = idTypeClient;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String toString(){
		return Integer.toString(this.idTypeClient)+" "+this.nom;
	}
	public static ArrayList<TypeClient> selectTypeClient(Connection conn){
		Statement statement = null;
		ResultSet resultat= null;
		ArrayList<TypeClient> typeClients=new ArrayList<TypeClient>();
		try {
			statement = conn.createStatement();

	        /* Exécution d'une requète de lecture */
	        resultat = statement.executeQuery( "select * from type_client" );
	 
	        /* Récupération des données du résultat de la requète de lecture */
	        while ( resultat.next() ) {
	        	typeClients.add(new TypeClient(Integer.parseInt(resultat.getString(1)),resultat.getString(2)));
		}
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
        
		return typeClients;
	}

}
